## STATIC CONFIGURATION
log:
  level: DEBUG

api:                                                                                # Both settings are only necessary if you use the Dashboard at all. Turn off when done configuring.
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      middlewares:
        - secHeaders@file
        - rate_limit@file

  traefik:                                                                          # Only necessary if you plan to access the Traefik Dashboard.
    address: ":8888"

providers:
  docker:
    watch: true
    endpoint: "tcp://<IP>:2375"                                                     # Replace IP address for Docker Socket proxy (recommended). Alternatively with "unix:///var/run/docker.sock".
    exposedByDefault: false
  file:
#    filename: "/etc/traefik/dynamic.yml"                                           # Uncomment in order to use one dynamic configuration file
    folder: "etc/traefik/dynamic"                                                   # Uses a folder to watch for dynamic configurations. All .yaml files will be watched and added automatically
    watch: true

certificatesResolvers:

    cloudflare:
      acme:
        email: youremail@example.com                                                # Replace with your E-Mail.
        storage: "/etc/traefik/acme.json"
        dnsChallenge:
          provider: cloudflare
          resolvers:
            - "1.1.1.1:53"
            - "1.0.0.1:53"

# serversTransport:                                                                 # May be necessary for some services. If you see connection issues due to self-signed certificates of the host, uncomment this.
#  insecureSkipVerify: true            